Player
shloch/TIC-TAC-TOE pull request #1
Opened 2019-04-15 12:15 UTC by shloch

2019-04-15 19:01 UTC, inhaq requested changes
Hi, good attempt to Tic Tac Toe and welcome to the OOP. In order to practice OOP, you must understand SOLID principle. It's not always about making app works but rather following practices which will help you when you'll need to do modification later. Lesser you'll depends, less you'll need to change.

 - There is no need to add `Winnermodule` from another file as it's just one array.
 - In `player.rb` you're using two big functions, slice it down to small functions. Like `user_input', `display_msg` etc
 - `gameclass.rb` has class which can be further sliced to functionality and display messages. Consider putting them to separate classes.
 - In execution file i.e. `game.rb` there is display messages as well as game functionality, kindly use it for execution only rather than putting both into one file.

I'm not able to run this project since you're using gems but `Gemfile` is missing from repo. Kindly add `Gemfile` and resubmit for review.

2019-04-16 10:56 UTC, shloch commented
Thanks for the review....we proposed changes as demanded

2019-04-16 18:40 UTC, inhaq requested changes
Hi folks, nice try. But few of implementations from the last review wasn't done or done properly.
Update Gemfile to execute properly. Try to make your functions pure. It should do one job and do it very well. Try to not go over a few lines for every function.
Once updated, kindly submit for review.

2019-04-16 18:40 UTC, inhaq commented on lib/gameclass.rb
> +    puts "#{@@filling_array[0]} | #{@@filling_array[1]} | #{@@filling_array[2]}"
why use `@@` class variables?

2019-04-17 09:05 UTC, shloch commented on lib/gameclass.rb
> +    puts "#{@@filling_array[0]} | #{@@filling_array[1]} | #{@@filling_array[2]}"
changed

2019-04-17 19:08 UTC, inhaq requested changes
Hi guys, you're reaching the finishing line. Here are a few things to take care of:
 - Use specific names for files and functions. For example, two files are named as `game.rb` and `gameclass.rb`, try to be more specific about these classes and files.
 - Within `game.rb` and `player.rb` there is function `play`. Try to use a clearer name.
 - Both these functions should be sliced down to become pure function.

Once fixed, kindly submit for review.

2019-04-19 04:21 UTC, inhaq approved these changes
Hi folks, I understand that you're trying your best. But you're just changing minor things here and there and submit it again. This project is still not 100% and I would suggest doing these modifications before merging. I really want you guys to learn more and improve this project.
 - fix `rubocop` errors(it'll suggest slicing down the functions as well)
 - fix namings for the functions and classes. You can't name anything `gameClass` and then create player separately, it should be `player`, `board`, `messages` etc. And each class should responsible for their own functionalities. 
 - update `readme` as executable file isn't `game.rb` anymore.

Once fixed, merged the branch. No need to review from my side. Good luck 👍🏻

2019-04-19 10:51 UTC, shloch commented
thanks for the reviews...we learned many things

2019-04-19 12:11 UTC, merged